# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "8dev-bsp"
BBFILE_PATTERN_8dev-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_8dev-bsp = "6"

LAYERDEPENDS_8dev-bsp = "core openembedded-layer qcom"
LAYERSERIES_COMPAT_8dev-bsp = "scarthgap"
