# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "8dev-basic"
BBFILE_PATTERN_8dev-basic = "^${LAYERDIR}/"
BBFILE_PRIORITY_8dev-basic = "6"

LAYERDEPENDS_8dev-basic = "core networking-layer swupdate"
LAYERSERIES_COMPAT_8dev-basic = "scarthgap"
