#@TYPE: Machine
#@NAME: Robonode
#@DESCRIPTION: Machine configuration for the 8devices Robonode

require conf/machine/include/tobufi.inc

KERNEL_DEVICETREE = "\
    qcom/qcs405-8devices-robonode-rev2.dtb \
    qcom/qcs405-8devices-robonode.dtb \
"
