#@TYPE: Machine
#@NAME: TobuFi DVK
#@DESCRIPTION: Machine configuration for the 8devices TobuFi DVK

require conf/machine/include/tobufi.inc

KERNEL_DEVICETREE = "\
    qcom/qcs405-8devices-tobufi-dvk-rev4.dtb \
    qcom/qcs405-8devices-tobufi-dvk-rev3.dtb \
    qcom/qcs405-8devices-tobufi-dvk.dtb \
"
